CREATE TABLE Pokemon (	name varchar,
	id int,
	height varchar,
	weight int,
	ability varchar,
	species varchar,
	primary_type varchar,
	secondary_type varchar,
	official_artwork varchar
);
ALTER TABLE Pokemon ADD PRIMARY KEY (name);
CREATE TABLE Stats (	name varchar,
	hp int,
	attack int,
	defense int,
	special-attack int,
	special-defense int,
	speed int
);
ALTER TABLE Stats ADD PRIMARY KEY (name);
INSERT INTO Pokemon VALUES ('bulbasaur', 1, 7, 69, 'overgrow', 'Seed Pokémon', 'grass', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png');
INSERT INTO Stats VALUES ('bulbasaur', 45, 49, 49, 65, 65, 45);
INSERT INTO Pokemon VALUES ('ivysaur', 2, 10, 130, 'overgrow', 'Seed Pokémon', 'grass', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png');
INSERT INTO Stats VALUES ('ivysaur', 60, 62, 63, 80, 80, 60);
INSERT INTO Pokemon VALUES ('venusaur', 3, 20, 1000, 'overgrow', 'Seed Pokémon', 'grass', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png');
INSERT INTO Stats VALUES ('venusaur', 80, 82, 83, 100, 100, 80);
INSERT INTO Pokemon VALUES ('charmander', 4, 6, 85, 'blaze', 'Lizard Pokémon', 'fire', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png');
INSERT INTO Stats VALUES ('charmander', 39, 52, 43, 60, 50, 65);
INSERT INTO Pokemon VALUES ('charmeleon', 5, 11, 190, 'blaze', 'Flame Pokémon', 'fire', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png');
INSERT INTO Stats VALUES ('charmeleon', 58, 64, 58, 80, 65, 80);
INSERT INTO Pokemon VALUES ('charizard', 6, 17, 905, 'blaze', 'Flame Pokémon', 'fire', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png');
INSERT INTO Stats VALUES ('charizard', 78, 84, 78, 109, 85, 100);
INSERT INTO Pokemon VALUES ('squirtle', 7, 5, 90, 'torrent', 'Tiny Turtle Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png');
INSERT INTO Stats VALUES ('squirtle', 44, 48, 65, 50, 64, 43);
INSERT INTO Pokemon VALUES ('wartortle', 8, 10, 225, 'torrent', 'Turtle Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png');
INSERT INTO Stats VALUES ('wartortle', 59, 63, 80, 65, 80, 58);
INSERT INTO Pokemon VALUES ('blastoise', 9, 16, 855, 'torrent', 'Shellfish Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png');
INSERT INTO Stats VALUES ('blastoise', 79, 83, 100, 85, 105, 78);
INSERT INTO Pokemon VALUES ('caterpie', 10, 3, 29, 'shield-dust', 'Worm Pokémon', 'bug', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png');
INSERT INTO Stats VALUES ('caterpie', 45, 30, 35, 20, 20, 45);
INSERT INTO Pokemon VALUES ('metapod', 11, 7, 99, 'shed-skin', 'Cocoon Pokémon', 'bug', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png');
INSERT INTO Stats VALUES ('metapod', 50, 20, 55, 25, 25, 30);
INSERT INTO Pokemon VALUES ('butterfree', 12, 11, 320, 'compound-eyes', 'Butterfly Pokémon', 'bug', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png');
INSERT INTO Stats VALUES ('butterfree', 60, 45, 50, 90, 80, 70);
INSERT INTO Pokemon VALUES ('weedle', 13, 3, 32, 'shield-dust', 'Hairy Bug Pokémon', 'bug', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png');
INSERT INTO Stats VALUES ('weedle', 40, 35, 30, 20, 20, 50);
INSERT INTO Pokemon VALUES ('kakuna', 14, 6, 100, 'shed-skin', 'Cocoon Pokémon', 'bug', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png');
INSERT INTO Stats VALUES ('kakuna', 45, 25, 50, 25, 25, 35);
INSERT INTO Pokemon VALUES ('beedrill', 15, 10, 295, 'swarm', 'Poison Bee Pokémon', 'bug', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png');
INSERT INTO Stats VALUES ('beedrill', 65, 90, 40, 45, 80, 75);
INSERT INTO Pokemon VALUES ('pidgey', 16, 3, 18, 'keen-eye', 'Tiny Bird Pokémon', 'normal', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png');
INSERT INTO Stats VALUES ('pidgey', 40, 45, 40, 35, 35, 56);
INSERT INTO Pokemon VALUES ('pidgeotto', 17, 11, 300, 'keen-eye', 'Bird Pokémon', 'normal', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png');
INSERT INTO Stats VALUES ('pidgeotto', 63, 60, 55, 50, 50, 71);
INSERT INTO Pokemon VALUES ('pidgeot', 18, 15, 395, 'keen-eye', 'Bird Pokémon', 'normal', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png');
INSERT INTO Stats VALUES ('pidgeot', 83, 80, 75, 70, 70, 101);
INSERT INTO Pokemon VALUES ('rattata', 19, 3, 35, 'run-away', 'Mouse Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png');
INSERT INTO Stats VALUES ('rattata', 30, 56, 35, 25, 35, 72);
INSERT INTO Pokemon VALUES ('raticate', 20, 7, 185, 'run-away', 'Mouse Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png');
INSERT INTO Stats VALUES ('raticate', 55, 81, 60, 50, 70, 97);
INSERT INTO Pokemon VALUES ('spearow', 21, 3, 20, 'keen-eye', 'Tiny Bird Pokémon', 'normal', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png');
INSERT INTO Stats VALUES ('spearow', 40, 60, 30, 31, 31, 70);
INSERT INTO Pokemon VALUES ('fearow', 22, 12, 380, 'keen-eye', 'Beak Pokémon', 'normal', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png');
INSERT INTO Stats VALUES ('fearow', 65, 90, 65, 61, 61, 100);
INSERT INTO Pokemon VALUES ('ekans', 23, 20, 69, 'intimidate', 'Snake Pokémon', 'poison', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png');
INSERT INTO Stats VALUES ('ekans', 35, 60, 44, 40, 54, 55);
INSERT INTO Pokemon VALUES ('arbok', 24, 35, 650, 'intimidate', 'Cobra Pokémon', 'poison', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png');
INSERT INTO Stats VALUES ('arbok', 60, 95, 69, 65, 79, 80);
INSERT INTO Pokemon VALUES ('pikachu', 25, 4, 60, 'static', 'Mouse Pokémon', 'electric', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png');
INSERT INTO Stats VALUES ('pikachu', 35, 55, 40, 50, 50, 90);
INSERT INTO Pokemon VALUES ('raichu', 26, 8, 300, 'static', 'Mouse Pokémon', 'electric', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png');
INSERT INTO Stats VALUES ('raichu', 60, 90, 55, 90, 80, 110);
INSERT INTO Pokemon VALUES ('sandshrew', 27, 6, 120, 'sand-veil', 'Mouse Pokémon', 'ground', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png');
INSERT INTO Stats VALUES ('sandshrew', 50, 75, 85, 20, 30, 40);
INSERT INTO Pokemon VALUES ('sandslash', 28, 10, 295, 'sand-veil', 'Mouse Pokémon', 'ground', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png');
INSERT INTO Stats VALUES ('sandslash', 75, 100, 110, 45, 55, 65);
INSERT INTO Pokemon VALUES ('nidoran-f', 29, 4, 70, 'poison-point', 'Poison Pin Pokémon', 'poison', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png');
INSERT INTO Stats VALUES ('nidoran-f', 55, 47, 52, 40, 40, 41);
INSERT INTO Pokemon VALUES ('nidorina', 30, 8, 200, 'poison-point', 'Poison Pin Pokémon', 'poison', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png');
INSERT INTO Stats VALUES ('nidorina', 70, 62, 67, 55, 55, 56);
INSERT INTO Pokemon VALUES ('nidoqueen', 31, 13, 600, 'poison-point', 'Drill Pokémon', 'poison', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png');
INSERT INTO Stats VALUES ('nidoqueen', 90, 92, 87, 75, 85, 76);
INSERT INTO Pokemon VALUES ('nidoran-m', 32, 5, 90, 'poison-point', 'Poison Pin Pokémon', 'poison', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png');
INSERT INTO Stats VALUES ('nidoran-m', 46, 57, 40, 40, 40, 50);
INSERT INTO Pokemon VALUES ('nidorino', 33, 9, 195, 'poison-point', 'Poison Pin Pokémon', 'poison', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/33.png');
INSERT INTO Stats VALUES ('nidorino', 61, 72, 57, 55, 55, 65);
INSERT INTO Pokemon VALUES ('nidoking', 34, 14, 620, 'poison-point', 'Drill Pokémon', 'poison', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png');
INSERT INTO Stats VALUES ('nidoking', 81, 102, 77, 85, 75, 85);
INSERT INTO Pokemon VALUES ('clefairy', 35, 6, 75, 'cute-charm', 'Fairy Pokémon', 'fairy', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png');
INSERT INTO Stats VALUES ('clefairy', 70, 45, 48, 60, 65, 35);
INSERT INTO Pokemon VALUES ('clefable', 36, 13, 400, 'cute-charm', 'Fairy Pokémon', 'fairy', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/36.png');
INSERT INTO Stats VALUES ('clefable', 95, 70, 73, 95, 90, 60);
INSERT INTO Pokemon VALUES ('vulpix', 37, 6, 99, 'flash-fire', 'Fox Pokémon', 'fire', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png');
INSERT INTO Stats VALUES ('vulpix', 38, 41, 40, 50, 65, 65);
INSERT INTO Pokemon VALUES ('ninetales', 38, 11, 199, 'flash-fire', 'Fox Pokémon', 'fire', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png');
INSERT INTO Stats VALUES ('ninetales', 73, 76, 75, 81, 100, 100);
INSERT INTO Pokemon VALUES ('jigglypuff', 39, 5, 55, 'cute-charm', 'Balloon Pokémon', 'normal', 'fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png');
INSERT INTO Stats VALUES ('jigglypuff', 115, 45, 20, 45, 25, 20);
INSERT INTO Pokemon VALUES ('wigglytuff', 40, 10, 120, 'cute-charm', 'Balloon Pokémon', 'normal', 'fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/40.png');
INSERT INTO Stats VALUES ('wigglytuff', 140, 70, 45, 85, 50, 45);
INSERT INTO Pokemon VALUES ('zubat', 41, 8, 75, 'inner-focus', 'Bat Pokémon', 'poison', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png');
INSERT INTO Stats VALUES ('zubat', 40, 45, 35, 30, 40, 55);
INSERT INTO Pokemon VALUES ('golbat', 42, 16, 550, 'inner-focus', 'Bat Pokémon', 'poison', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png');
INSERT INTO Stats VALUES ('golbat', 75, 80, 70, 65, 75, 90);
INSERT INTO Pokemon VALUES ('oddish', 43, 5, 54, 'chlorophyll', 'Weed Pokémon', 'grass', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png');
INSERT INTO Stats VALUES ('oddish', 45, 50, 55, 75, 65, 30);
INSERT INTO Pokemon VALUES ('gloom', 44, 8, 86, 'chlorophyll', 'Weed Pokémon', 'grass', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/44.png');
INSERT INTO Stats VALUES ('gloom', 60, 65, 70, 85, 75, 40);
INSERT INTO Pokemon VALUES ('vileplume', 45, 12, 186, 'chlorophyll', 'Flower Pokémon', 'grass', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/45.png');
INSERT INTO Stats VALUES ('vileplume', 75, 80, 85, 110, 90, 50);
INSERT INTO Pokemon VALUES ('paras', 46, 3, 54, 'effect-spore', 'Mushroom Pokémon', 'bug', 'grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/46.png');
INSERT INTO Stats VALUES ('paras', 35, 70, 55, 45, 55, 25);
INSERT INTO Pokemon VALUES ('parasect', 47, 10, 295, 'effect-spore', 'Mushroom Pokémon', 'bug', 'grass', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/47.png');
INSERT INTO Stats VALUES ('parasect', 60, 95, 80, 60, 80, 30);
INSERT INTO Pokemon VALUES ('venonat', 48, 10, 300, 'compound-eyes', 'Insect Pokémon', 'bug', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/48.png');
INSERT INTO Stats VALUES ('venonat', 60, 55, 50, 40, 55, 45);
INSERT INTO Pokemon VALUES ('venomoth', 49, 15, 125, 'shield-dust', 'Poison Moth Pokémon', 'bug', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/49.png');
INSERT INTO Stats VALUES ('venomoth', 70, 65, 60, 90, 75, 90);
INSERT INTO Pokemon VALUES ('diglett', 50, 2, 8, 'sand-veil', 'Mole Pokémon', 'ground', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png');
INSERT INTO Stats VALUES ('diglett', 10, 55, 25, 35, 45, 95);
INSERT INTO Pokemon VALUES ('dugtrio', 51, 7, 333, 'sand-veil', 'Mole Pokémon', 'ground', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png');
INSERT INTO Stats VALUES ('dugtrio', 35, 100, 50, 50, 70, 120);
INSERT INTO Pokemon VALUES ('meowth', 52, 4, 42, 'pickup', 'Scratch Cat Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png');
INSERT INTO Stats VALUES ('meowth', 40, 45, 35, 40, 40, 90);
INSERT INTO Pokemon VALUES ('persian', 53, 10, 320, 'limber', 'Classy Cat Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png');
INSERT INTO Stats VALUES ('persian', 65, 70, 60, 65, 65, 115);
INSERT INTO Pokemon VALUES ('psyduck', 54, 8, 196, 'damp', 'Duck Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png');
INSERT INTO Stats VALUES ('psyduck', 50, 52, 48, 65, 50, 55);
INSERT INTO Pokemon VALUES ('golduck', 55, 17, 766, 'damp', 'Duck Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png');
INSERT INTO Stats VALUES ('golduck', 80, 82, 78, 95, 80, 85);
INSERT INTO Pokemon VALUES ('mankey', 56, 5, 280, 'vital-spirit', 'Pig Monkey Pokémon', 'fighting', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png');
INSERT INTO Stats VALUES ('mankey', 40, 80, 35, 35, 45, 70);
INSERT INTO Pokemon VALUES ('primeape', 57, 10, 320, 'vital-spirit', 'Pig Monkey Pokémon', 'fighting', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/57.png');
INSERT INTO Stats VALUES ('primeape', 65, 105, 60, 60, 70, 95);
INSERT INTO Pokemon VALUES ('growlithe', 58, 7, 190, 'intimidate', 'Puppy Pokémon', 'fire', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png');
INSERT INTO Stats VALUES ('growlithe', 55, 70, 45, 70, 50, 60);
INSERT INTO Pokemon VALUES ('arcanine', 59, 19, 1550, 'intimidate', 'Legendary Pokémon', 'fire', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png');
INSERT INTO Stats VALUES ('arcanine', 90, 110, 80, 100, 80, 95);
INSERT INTO Pokemon VALUES ('poliwag', 60, 6, 124, 'water-absorb', 'Tadpole Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png');
INSERT INTO Stats VALUES ('poliwag', 40, 50, 40, 40, 40, 90);
INSERT INTO Pokemon VALUES ('poliwhirl', 61, 10, 200, 'water-absorb', 'Tadpole Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/61.png');
INSERT INTO Stats VALUES ('poliwhirl', 65, 65, 65, 50, 50, 90);
INSERT INTO Pokemon VALUES ('poliwrath', 62, 13, 540, 'water-absorb', 'Tadpole Pokémon', 'water', 'fighting', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/62.png');
INSERT INTO Stats VALUES ('poliwrath', 90, 95, 95, 70, 90, 70);
INSERT INTO Pokemon VALUES ('abra', 63, 9, 195, 'synchronize', 'Psi Pokémon', 'psychic', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png');
INSERT INTO Stats VALUES ('abra', 25, 20, 15, 105, 55, 90);
INSERT INTO Pokemon VALUES ('kadabra', 64, 13, 565, 'synchronize', 'Psi Pokémon', 'psychic', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png');
INSERT INTO Stats VALUES ('kadabra', 40, 35, 30, 120, 70, 105);
INSERT INTO Pokemon VALUES ('alakazam', 65, 15, 480, 'synchronize', 'Psi Pokémon', 'psychic', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png');
INSERT INTO Stats VALUES ('alakazam', 55, 50, 45, 135, 95, 120);
INSERT INTO Pokemon VALUES ('machop', 66, 8, 195, 'guts', 'Superpower Pokémon', 'fighting', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png');
INSERT INTO Stats VALUES ('machop', 70, 80, 50, 35, 35, 35);
INSERT INTO Pokemon VALUES ('machoke', 67, 15, 705, 'guts', 'Superpower Pokémon', 'fighting', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png');
INSERT INTO Stats VALUES ('machoke', 80, 100, 70, 50, 60, 45);
INSERT INTO Pokemon VALUES ('machamp', 68, 16, 1300, 'guts', 'Superpower Pokémon', 'fighting', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png');
INSERT INTO Stats VALUES ('machamp', 90, 130, 80, 65, 85, 55);
INSERT INTO Pokemon VALUES ('bellsprout', 69, 7, 40, 'chlorophyll', 'Flower Pokémon', 'grass', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png');
INSERT INTO Stats VALUES ('bellsprout', 50, 75, 35, 70, 30, 40);
INSERT INTO Pokemon VALUES ('weepinbell', 70, 10, 64, 'chlorophyll', 'Flycatcher Pokémon', 'grass', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png');
INSERT INTO Stats VALUES ('weepinbell', 65, 90, 50, 85, 45, 55);
INSERT INTO Pokemon VALUES ('victreebel', 71, 17, 155, 'chlorophyll', 'Flycatcher Pokémon', 'grass', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png');
INSERT INTO Stats VALUES ('victreebel', 80, 105, 65, 100, 70, 70);
INSERT INTO Pokemon VALUES ('tentacool', 72, 9, 455, 'clear-body', 'Jellyfish Pokémon', 'water', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png');
INSERT INTO Stats VALUES ('tentacool', 40, 40, 35, 50, 100, 70);
INSERT INTO Pokemon VALUES ('tentacruel', 73, 16, 550, 'clear-body', 'Jellyfish Pokémon', 'water', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png');
INSERT INTO Stats VALUES ('tentacruel', 80, 70, 65, 80, 120, 100);
INSERT INTO Pokemon VALUES ('geodude', 74, 4, 200, 'rock-head', 'Rock Pokémon', 'rock', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png');
INSERT INTO Stats VALUES ('geodude', 40, 80, 100, 30, 30, 20);
INSERT INTO Pokemon VALUES ('graveler', 75, 10, 1050, 'rock-head', 'Rock Pokémon', 'rock', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png');
INSERT INTO Stats VALUES ('graveler', 55, 95, 115, 45, 45, 35);
INSERT INTO Pokemon VALUES ('golem', 76, 14, 3000, 'rock-head', 'Megaton Pokémon', 'rock', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png');
INSERT INTO Stats VALUES ('golem', 80, 120, 130, 55, 65, 45);
INSERT INTO Pokemon VALUES ('ponyta', 77, 10, 300, 'run-away', 'Fire Horse Pokémon', 'fire', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/77.png');
INSERT INTO Stats VALUES ('ponyta', 50, 85, 55, 65, 65, 90);
INSERT INTO Pokemon VALUES ('rapidash', 78, 17, 950, 'run-away', 'Fire Horse Pokémon', 'fire', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/78.png');
INSERT INTO Stats VALUES ('rapidash', 65, 100, 70, 80, 80, 105);
INSERT INTO Pokemon VALUES ('slowpoke', 79, 12, 360, 'oblivious', 'Dopey Pokémon', 'water', 'psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png');
INSERT INTO Stats VALUES ('slowpoke', 90, 65, 65, 40, 40, 15);
INSERT INTO Pokemon VALUES ('slowbro', 80, 16, 785, 'oblivious', 'Hermit Crab Pokémon', 'water', 'psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png');
INSERT INTO Stats VALUES ('slowbro', 95, 75, 110, 100, 80, 30);
INSERT INTO Pokemon VALUES ('magnemite', 81, 3, 60, 'magnet-pull', 'Magnet Pokémon', 'electric', 'steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png');
INSERT INTO Stats VALUES ('magnemite', 25, 35, 70, 95, 55, 45);
INSERT INTO Pokemon VALUES ('magneton', 82, 10, 600, 'magnet-pull', 'Magnet Pokémon', 'electric', 'steel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/82.png');
INSERT INTO Stats VALUES ('magneton', 50, 60, 95, 120, 70, 70);
INSERT INTO Pokemon VALUES ('farfetchd', 83, 8, 150, 'keen-eye', 'Wild Duck Pokémon', 'normal', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/83.png');
INSERT INTO Stats VALUES ('farfetchd', 52, 90, 55, 58, 62, 60);
INSERT INTO Pokemon VALUES ('doduo', 84, 14, 392, 'run-away', 'Twin Bird Pokémon', 'normal', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png');
INSERT INTO Stats VALUES ('doduo', 35, 85, 45, 35, 35, 75);
INSERT INTO Pokemon VALUES ('dodrio', 85, 18, 852, 'run-away', 'Triple Bird Pokémon', 'normal', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png');
INSERT INTO Stats VALUES ('dodrio', 60, 110, 70, 60, 60, 110);
INSERT INTO Pokemon VALUES ('seel', 86, 11, 900, 'thick-fat', 'Sea Lion Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/86.png');
INSERT INTO Stats VALUES ('seel', 65, 45, 55, 45, 70, 45);
INSERT INTO Pokemon VALUES ('dewgong', 87, 17, 1200, 'thick-fat', 'Sea Lion Pokémon', 'water', 'ice', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/87.png');
INSERT INTO Stats VALUES ('dewgong', 90, 70, 80, 70, 95, 70);
INSERT INTO Pokemon VALUES ('grimer', 88, 9, 300, 'stench', 'Sludge Pokémon', 'poison', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png');
INSERT INTO Stats VALUES ('grimer', 80, 80, 50, 40, 50, 25);
INSERT INTO Pokemon VALUES ('muk', 89, 12, 300, 'stench', 'Sludge Pokémon', 'poison', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/89.png');
INSERT INTO Stats VALUES ('muk', 105, 105, 75, 65, 100, 50);
INSERT INTO Pokemon VALUES ('shellder', 90, 3, 40, 'shell-armor', 'Bivalve Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png');
INSERT INTO Stats VALUES ('shellder', 30, 65, 100, 45, 25, 40);
INSERT INTO Pokemon VALUES ('cloyster', 91, 15, 1325, 'shell-armor', 'Bivalve Pokémon', 'water', 'ice', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png');
INSERT INTO Stats VALUES ('cloyster', 50, 95, 180, 85, 45, 70);
INSERT INTO Pokemon VALUES ('gastly', 92, 13, 1, 'levitate', 'Gas Pokémon', 'ghost', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png');
INSERT INTO Stats VALUES ('gastly', 30, 35, 30, 100, 35, 80);
INSERT INTO Pokemon VALUES ('haunter', 93, 16, 1, 'levitate', 'Gas Pokémon', 'ghost', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png');
INSERT INTO Stats VALUES ('haunter', 45, 50, 45, 115, 55, 95);
INSERT INTO Pokemon VALUES ('gengar', 94, 15, 405, 'cursed-body', 'Shadow Pokémon', 'ghost', 'poison', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png');
INSERT INTO Stats VALUES ('gengar', 60, 65, 60, 130, 75, 110);
INSERT INTO Pokemon VALUES ('onix', 95, 88, 2100, 'rock-head', 'Rock Snake Pokémon', 'rock', 'ground', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png');
INSERT INTO Stats VALUES ('onix', 35, 45, 160, 30, 45, 70);
INSERT INTO Pokemon VALUES ('drowzee', 96, 10, 324, 'insomnia', 'Hypnosis Pokémon', 'psychic', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png');
INSERT INTO Stats VALUES ('drowzee', 60, 48, 45, 43, 90, 42);
INSERT INTO Pokemon VALUES ('hypno', 97, 16, 756, 'insomnia', 'Hypnosis Pokémon', 'psychic', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png');
INSERT INTO Stats VALUES ('hypno', 85, 73, 70, 73, 115, 67);
INSERT INTO Pokemon VALUES ('krabby', 98, 4, 65, 'hyper-cutter', 'River Crab Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png');
INSERT INTO Stats VALUES ('krabby', 30, 105, 90, 25, 25, 50);
INSERT INTO Pokemon VALUES ('kingler', 99, 13, 600, 'hyper-cutter', 'Pincer Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png');
INSERT INTO Stats VALUES ('kingler', 55, 130, 115, 50, 50, 75);
INSERT INTO Pokemon VALUES ('voltorb', 100, 5, 104, 'soundproof', 'Ball Pokémon', 'electric', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png');
INSERT INTO Stats VALUES ('voltorb', 40, 30, 50, 55, 55, 100);
INSERT INTO Pokemon VALUES ('electrode', 101, 12, 666, 'soundproof', 'Ball Pokémon', 'electric', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/101.png');
INSERT INTO Stats VALUES ('electrode', 60, 50, 70, 80, 80, 150);
INSERT INTO Pokemon VALUES ('exeggcute', 102, 4, 25, 'chlorophyll', 'Egg Pokémon', 'grass', 'psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png');
INSERT INTO Stats VALUES ('exeggcute', 60, 40, 80, 60, 45, 40);
INSERT INTO Pokemon VALUES ('exeggutor', 103, 20, 1200, 'chlorophyll', 'Coconut Pokémon', 'grass', 'psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png');
INSERT INTO Stats VALUES ('exeggutor', 95, 95, 85, 125, 75, 55);
INSERT INTO Pokemon VALUES ('cubone', 104, 4, 65, 'rock-head', 'Lonely Pokémon', 'ground', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png');
INSERT INTO Stats VALUES ('cubone', 50, 50, 95, 40, 50, 35);
INSERT INTO Pokemon VALUES ('marowak', 105, 10, 450, 'rock-head', 'Bone Keeper Pokémon', 'ground', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png');
INSERT INTO Stats VALUES ('marowak', 60, 80, 110, 50, 80, 45);
INSERT INTO Pokemon VALUES ('hitmonlee', 106, 15, 498, 'limber', 'Kicking Pokémon', 'fighting', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png');
INSERT INTO Stats VALUES ('hitmonlee', 50, 120, 53, 35, 110, 87);
INSERT INTO Pokemon VALUES ('hitmonchan', 107, 14, 502, 'keen-eye', 'Punching Pokémon', 'fighting', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png');
INSERT INTO Stats VALUES ('hitmonchan', 50, 105, 79, 35, 110, 76);
INSERT INTO Pokemon VALUES ('lickitung', 108, 12, 655, 'own-tempo', 'Licking Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/108.png');
INSERT INTO Stats VALUES ('lickitung', 90, 55, 75, 60, 75, 30);
INSERT INTO Pokemon VALUES ('koffing', 109, 6, 10, 'levitate', 'Poison Gas Pokémon', 'poison', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png');
INSERT INTO Stats VALUES ('koffing', 40, 65, 95, 60, 45, 35);
INSERT INTO Pokemon VALUES ('weezing', 110, 12, 95, 'levitate', 'Poison Gas Pokémon', 'poison', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png');
INSERT INTO Stats VALUES ('weezing', 65, 90, 120, 85, 70, 60);
INSERT INTO Pokemon VALUES ('rhyhorn', 111, 10, 1150, 'lightning-rod', 'Spikes Pokémon', 'ground', 'rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png');
INSERT INTO Stats VALUES ('rhyhorn', 80, 85, 95, 30, 30, 25);
INSERT INTO Pokemon VALUES ('rhydon', 112, 19, 1200, 'lightning-rod', 'Drill Pokémon', 'ground', 'rock', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png');
INSERT INTO Stats VALUES ('rhydon', 105, 130, 120, 45, 45, 40);
INSERT INTO Pokemon VALUES ('chansey', 113, 11, 346, 'natural-cure', 'Egg Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png');
INSERT INTO Stats VALUES ('chansey', 250, 5, 5, 35, 105, 50);
INSERT INTO Pokemon VALUES ('tangela', 114, 10, 350, 'chlorophyll', 'Vine Pokémon', 'grass', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png');
INSERT INTO Stats VALUES ('tangela', 65, 55, 115, 100, 40, 60);
INSERT INTO Pokemon VALUES ('kangaskhan', 115, 22, 800, 'early-bird', 'Parent Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/115.png');
INSERT INTO Stats VALUES ('kangaskhan', 105, 95, 80, 40, 80, 90);
INSERT INTO Pokemon VALUES ('horsea', 116, 4, 80, 'swift-swim', 'Dragon Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/116.png');
INSERT INTO Stats VALUES ('horsea', 30, 40, 70, 70, 25, 60);
INSERT INTO Pokemon VALUES ('seadra', 117, 12, 250, 'poison-point', 'Dragon Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/117.png');
INSERT INTO Stats VALUES ('seadra', 55, 65, 95, 95, 45, 85);
INSERT INTO Pokemon VALUES ('goldeen', 118, 6, 150, 'swift-swim', 'Goldfish Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/118.png');
INSERT INTO Stats VALUES ('goldeen', 45, 67, 60, 35, 50, 63);
INSERT INTO Pokemon VALUES ('seaking', 119, 13, 390, 'swift-swim', 'Goldfish Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/119.png');
INSERT INTO Stats VALUES ('seaking', 80, 92, 65, 65, 80, 68);
INSERT INTO Pokemon VALUES ('staryu', 120, 8, 345, 'illuminate', 'Star Shape Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png');
INSERT INTO Stats VALUES ('staryu', 30, 45, 55, 70, 55, 85);
INSERT INTO Pokemon VALUES ('starmie', 121, 11, 800, 'illuminate', 'Mysterious Pokémon', 'water', 'psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png');
INSERT INTO Stats VALUES ('starmie', 60, 75, 85, 100, 85, 115);
INSERT INTO Pokemon VALUES ('mr-mime', 122, 13, 545, 'soundproof', 'Barrier Pokémon', 'psychic', 'fairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png');
INSERT INTO Stats VALUES ('mr-mime', 40, 45, 65, 100, 120, 90);
INSERT INTO Pokemon VALUES ('scyther', 123, 15, 560, 'swarm', 'Mantis Pokémon', 'bug', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/123.png');
INSERT INTO Stats VALUES ('scyther', 70, 110, 80, 55, 80, 105);
INSERT INTO Pokemon VALUES ('jynx', 124, 14, 406, 'oblivious', 'Human Shape Pokémon', 'ice', 'psychic', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/124.png');
INSERT INTO Stats VALUES ('jynx', 65, 50, 35, 115, 95, 95);
INSERT INTO Pokemon VALUES ('electabuzz', 125, 11, 300, 'static', 'Electric Pokémon', 'electric', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png');
INSERT INTO Stats VALUES ('electabuzz', 65, 83, 57, 95, 85, 105);
INSERT INTO Pokemon VALUES ('magmar', 126, 13, 445, 'flame-body', 'Spitfire Pokémon', 'fire', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/126.png');
INSERT INTO Stats VALUES ('magmar', 65, 95, 57, 100, 85, 93);
INSERT INTO Pokemon VALUES ('pinsir', 127, 15, 550, 'hyper-cutter', 'Stag Beetle Pokémon', 'bug', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/127.png');
INSERT INTO Stats VALUES ('pinsir', 65, 125, 100, 55, 70, 85);
INSERT INTO Pokemon VALUES ('tauros', 128, 14, 884, 'intimidate', 'Wild Bull Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/128.png');
INSERT INTO Stats VALUES ('tauros', 75, 100, 95, 40, 70, 110);
INSERT INTO Pokemon VALUES ('magikarp', 129, 9, 100, 'swift-swim', 'Fish Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png');
INSERT INTO Stats VALUES ('magikarp', 20, 10, 55, 15, 20, 80);
INSERT INTO Pokemon VALUES ('gyarados', 130, 65, 2350, 'intimidate', 'Atrocious Pokémon', 'water', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png');
INSERT INTO Stats VALUES ('gyarados', 95, 125, 79, 60, 100, 81);
INSERT INTO Pokemon VALUES ('lapras', 131, 25, 2200, 'water-absorb', 'Transport Pokémon', 'water', 'ice', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png');
INSERT INTO Stats VALUES ('lapras', 130, 85, 80, 85, 95, 60);
INSERT INTO Pokemon VALUES ('ditto', 132, 3, 40, 'limber', 'Transform Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png');
INSERT INTO Stats VALUES ('ditto', 48, 48, 48, 48, 48, 48);
INSERT INTO Pokemon VALUES ('eevee', 133, 3, 65, 'run-away', 'Evolution Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png');
INSERT INTO Stats VALUES ('eevee', 55, 55, 50, 45, 65, 55);
INSERT INTO Pokemon VALUES ('vaporeon', 134, 10, 290, 'water-absorb', 'Bubble Jet Pokémon', 'water', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png');
INSERT INTO Stats VALUES ('vaporeon', 130, 65, 60, 110, 95, 65);
INSERT INTO Pokemon VALUES ('jolteon', 135, 8, 245, 'volt-absorb', 'Lightning Pokémon', 'electric', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png');
INSERT INTO Stats VALUES ('jolteon', 65, 65, 60, 110, 95, 130);
INSERT INTO Pokemon VALUES ('flareon', 136, 9, 250, 'flash-fire', 'Flame Pokémon', 'fire', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png');
INSERT INTO Stats VALUES ('flareon', 65, 130, 60, 95, 110, 65);
INSERT INTO Pokemon VALUES ('porygon', 137, 8, 365, 'trace', 'Virtual Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/137.png');
INSERT INTO Stats VALUES ('porygon', 65, 60, 70, 85, 75, 40);
INSERT INTO Pokemon VALUES ('omanyte', 138, 4, 75, 'swift-swim', 'Spiral Pokémon', 'rock', 'water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png');
INSERT INTO Stats VALUES ('omanyte', 35, 40, 100, 90, 55, 35);
INSERT INTO Pokemon VALUES ('omastar', 139, 10, 350, 'swift-swim', 'Spiral Pokémon', 'rock', 'water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png');
INSERT INTO Stats VALUES ('omastar', 70, 60, 125, 115, 70, 55);
INSERT INTO Pokemon VALUES ('kabuto', 140, 5, 115, 'swift-swim', 'Shellfish Pokémon', 'rock', 'water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png');
INSERT INTO Stats VALUES ('kabuto', 30, 80, 90, 55, 45, 55);
INSERT INTO Pokemon VALUES ('kabutops', 141, 13, 405, 'swift-swim', 'Shellfish Pokémon', 'rock', 'water', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png');
INSERT INTO Stats VALUES ('kabutops', 60, 115, 105, 65, 70, 80);
INSERT INTO Pokemon VALUES ('aerodactyl', 142, 18, 590, 'rock-head', 'Fossil Pokémon', 'rock', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/142.png');
INSERT INTO Stats VALUES ('aerodactyl', 80, 105, 65, 60, 75, 130);
INSERT INTO Pokemon VALUES ('snorlax', 143, 21, 4600, 'immunity', 'Sleeping Pokémon', 'normal', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png');
INSERT INTO Stats VALUES ('snorlax', 160, 110, 65, 65, 110, 30);
INSERT INTO Pokemon VALUES ('articuno', 144, 17, 554, 'pressure', 'Freeze Pokémon', 'ice', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png');
INSERT INTO Stats VALUES ('articuno', 90, 85, 100, 95, 125, 85);
INSERT INTO Pokemon VALUES ('zapdos', 145, 16, 526, 'pressure', 'Electric Pokémon', 'electric', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png');
INSERT INTO Stats VALUES ('zapdos', 90, 90, 85, 125, 90, 100);
INSERT INTO Pokemon VALUES ('moltres', 146, 20, 600, 'pressure', 'Flame Pokémon', 'fire', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png');
INSERT INTO Stats VALUES ('moltres', 90, 100, 90, 125, 85, 90);
INSERT INTO Pokemon VALUES ('dratini', 147, 18, 33, 'shed-skin', 'Dragon Pokémon', 'dragon', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png');
INSERT INTO Stats VALUES ('dratini', 41, 64, 45, 50, 50, 50);
INSERT INTO Pokemon VALUES ('dragonair', 148, 40, 165, 'shed-skin', 'Dragon Pokémon', 'dragon', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png');
INSERT INTO Stats VALUES ('dragonair', 61, 84, 65, 70, 70, 70);
INSERT INTO Pokemon VALUES ('dragonite', 149, 22, 2100, 'inner-focus', 'Dragon Pokémon', 'dragon', 'flying', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png');
INSERT INTO Stats VALUES ('dragonite', 91, 134, 95, 100, 100, 80);
INSERT INTO Pokemon VALUES ('mewtwo', 150, 20, 1220, 'pressure', 'Genetic Pokémon', 'psychic', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png');
INSERT INTO Stats VALUES ('mewtwo', 106, 110, 90, 154, 90, 130);
INSERT INTO Pokemon VALUES ('mew', 151, 4, 40, 'synchronize', 'New Species Pokémon', 'psychic', 'none', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png');
INSERT INTO Stats VALUES ('mew', 100, 100, 100, 100, 100, 100);
